//
//  Levels.swift
//  StackViewTest
//
//  Created by Ruslan Gritsenko on 4/15/19.
//  Copyright © 2019 Ruslan Gritsenko. All rights reserved.
//

import Foundation

struct LevelParameters {
    
    let colorModeFor = (cellsForLevel: [0  : true,
                                        1  : false,
                                        2  : true,
                                        3  : false,
                                        4  : false,
                                        5  : true,
                                        6  : false,
                                        7  : true,
                                        8  : false,
                                        9  : true,
                                        10 : true,
                                        11 : false,
                                        12 : false,
                                        13 : false,
                                        14 : true,
                                        15 : false,
                                        16 : false,
                                        17 : false,
                                        18 : true,
                                        19 : true,
                                        20 : true,
                                        21 : false,
                                        22 : true,
                                        23 : false,
                                        24 : true,
                                        25 : true,
                                        26 : true,
                                        27 : true,
                                        28 : true,
                                        29 : true,
                                        30 : true],
                        
                        numbersForLevel: [0  : true,
                                          1  : false,
                                          2  : false,
                                          3  : false,
                                          4  : false,
                                          5  : true,
                                          6  : false,
                                          7  : false,
                                          8  : false,
                                          9  : true,
                                          10 : true,
                                          11 : false,
                                          12 : false,
                                          13 : false,
                                          14 : false,
                                          15 : false,
                                          16 : false,
                                          17 : false,
                                          18 : true,
                                          19 : true,
                                          20 : true,
                                          21 : false,
                                          22 : false,
                                          23 : false,
                                          24 : true,
                                          25 : true,
                                          26 : true,
                                          27 : true,
                                          28 : true,
                                          29 : true,
                                          30 : true])
    
    let numbersCountForLevel = [0  : 40,
                                1  : 25,
                                2  : 25,
                                3  : 25,
                                4  : 30,
                                5  : 25,
                                6  : 25,
                                7  : 30,
                                8  : 25,
                                9  : 30,
                                10 : 25,
                                11 : 35,
                                12 : 30,
                                13 : 30,
                                14 : 35,
                                15 : 40,
                                16 : 35,
                                17 : 30,
                                18 : 35,
                                19 : 30,
                                20 : 25,
                                21 : 35,
                                22 : 40,
                                23 : 35,
                                24 : 30,
                                25 : 35,
                                26 : 40,
                                27 : 40,
                                28 : 35,
                                29 : 40,
                                30 : 40]
    
    let winkModeForLevel = [0  : false,
                            1  : false,
                            2  : false,
                            3  : true,
                            4  : false,
                            5  : false,
                            6  : false,
                            7  : false,
                            8  : false,
                            9  : false,
                            10 : true,
                            11 : false,
                            12 : true,
                            13 : false,
                            14 : false,
                            15 : false,
                            16 : true,
                            17 : false,
                            18 : false,
                            19 : true,
                            20 : true,
                            21 : false,
                            22 : false,
                            23 : false,
                            24 : true,
                            25 : true,
                            26 : false,
                            27 : true,
                            28 : true,
                            29 : true,
                            30 : true]
    
    let swapModeForLevel = [0  : false,
                            1  : false,
                            2  : false,
                            3  : false,
                            4  : false,
                            5  : false,
                            6  : false,
                            7  : false,
                            8  : true,
                            9  : false,
                            10 : false,
                            11 : false,
                            12 : false,
                            13 : false,
                            14 : false,
                            15 : false,
                            16 : false,
                            17 : true,
                            18 : false,
                            19 : false,
                            20 : false,
                            21 : false,
                            22 : false,
                            23 : true,
                            24 : false,
                            25 : false,
                            26 : false,
                            27 : false,
                            28 : false,
                            29 : true,
                            30 : false]
    
    let shuffleModeForLevel = [0  : false,
                               1  : false,
                               2  : false,
                               3  : false,
                               4  : false,
                               5  : false,
                               6  : true,
                               7  : false,
                               8  : false,
                               9  : false,
                               10 : false,
                               11 : false,
                               12 : false,
                               13 : true,
                               14 : false,
                               15 : false,
                               16 : false,
                               17 : false,
                               18 : false,
                               19 : false,
                               20 : true,
                               21 : true,
                               22 : false,
                               23 : false,
                               24 : true,
                               25 : false,
                               26 : false,
                               27 : false,
                               28 : true,
                               29 : false,
                               30 : true]
    
    let goalForLevel = [0  : 5.0,
                        1  : 27.5,
                        2  : 34.0,
                        3  : 35.5,
                        4  : 37.5,
                        5  : 40.0,
                        6  : 43.0,
                        7  : 43.5,
                        8  : 45.5,
                        9  : 51.5,
                        10 : 52.0,
                        11 : 53.0,
                        12 : 54.0,
                        13 : 55.0,
                        14 : 59.5,
                        15 : 62.5,
                        16 : 63.0,
                        17 : 63.0,
                        18 : 68.0,
                        19 : 68.0,
                        20 : 70.0,
                        21 : 70.5,
                        22 : 75.0,
                        23 : 77.0,
                        24 : 85.0,
                        25 : 95.0,
                        26 : 95.5,
                        27 : 129.0,
                        28 : 136.5,
                        29 : 142.0,
                        30 : 167.0]
    
}
