update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Taking screenshots"
  lane :take_screenshots do
    snapshot
  end

  desc "Create ipa"
  lane :build do
    enable_automatic_code_signing
    gym
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

end
