devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPad Pro (11-inch) (1st generation)",
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPad Pro (9.7-inch)"
])

languages([
  "en-US",
  "uk-UA",
  "ru-RU"
])

scheme("Fastlane UITests")

output_directory("./screenshots")

clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
